---

- name: make configured config_dir
  file:
    dest: "{{ consul.config.dir }}"
    state: present
    type: directory
    recurse: yes

- name: make configured data_dir
  file:
    dest: "{{ consul.config.data_dir }}"
    state: present
    type: directory
    recurse: yes
  when: consul.apply

- name: apply _server.json file
  template:
    src: _server.json.j2
    dest: "{{ consul.config.dir }}"
  when: consul.apply

- name: apply systemd service file
  template:
    src: consul.service.j2
    dest: /usr/lib/systemd/system/consul.service

- name: enable consul service
  systemd:
    name: consul.service
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
