---

- name: create consul user
  user:
    name: consul
    home: "{{ consul_config_path }}"
    system: yes

- name: make configured config_dir
  file:
    dest: "{{ consul_config_path }}/"
    state: directory
    owner: consul
    group: consul

- name: make configured data_dir
  file:
    dest: "{{ consul_server.data_dir }}/"
    state: directory
    owner: consul
    group: consul
  when: use_consul_server

- name: apply _server.json file
  template:
    src: _server.hcl.j2
    dest: "{{ consul_config_path }}/"
    owner: consul
    group: consul
  when: use_consul_server

- name: apply systemd service file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  notify: enable consul

