---

- name: make configured config_dir
  file:
    dest: "{{ consul_config_path }}/"
    state: directory
    recurse: yes

- name: make configured data_dir
  file:
    dest: "{{ consul_server.data_dir }}/"
    state: directory
    recurse: yes
  when: use_consul_server

- name: apply _server.json file
  template:
    src: _server.json.j2
    dest: "{{ consul_config_path }}/"
  when: use_consul_server

- name: apply systemd service file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  notify: enable consul
