---

- name: get platform
  set_fact:
    consul_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: get platform
  set_fact:
    consul_arch: "{{ ansible_architecture }}"
  when:
    - ansible_architecture != "x86_64"
    - ansible_architecture != "x86"

- name: extract and install consul
  unarchive:
    src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch }}.zip"
    dest: "{{ consul_bin_path }}/"
    remote_src: yes
